#ifndef KEYS_H_
#define KEYS_H_

enum {
 	DEPARTURE_KEY_FROM = 0x0,
	DEPARTURE_KEY_DESTINATION = 0x1,
	DEPARTURE_KEY_EXP_DEPARTURE = 0x2,
	DEPARTURE_KEY_PLATFORM = 0x3,
	DEPARTURE_KEY_FETCH = 0x4,
	GET_STATIONS_KEY_FETCH = 0x5,
	GET_STATIONS_KEY_STATION = 0x6,
	GET_STATIONS_KEY_SET_DISTANCE = 0x7
};

#endif